### ISSUE TITLE
Some question about urdf_gen.py

### ISSUE THREAD

**Issue by lihaosheng191240022** [zdchan/GraspXL#8]
Amazing work!
But I have a question about the code in the urdf_gen.py. Could you tell me why you use the cube.obj as the collision shape of the link "bottom" and what is use of the link "bottle". Thank you so much.

the code mentioned is in the line 45 of  urdf_gen.py
'''
bottom_obj_path = os.path.join(destination_folder, 'bottom.obj')
shutil.copyfile('cube.obj', bottom_obj_path)
'''

**Comment by zdchan** [comment]
Hi Haosheng,

Thanks for your interest in our work and thanks for asking. The cube.obj serves as a virtual link which does not have any collision body defined in the urdf. We utilize it for the bottom link to unify the framework of generation and loading of the urdf for articulated and rigid objects. To be more detailed, rigid objects will be the top link, with the cube.obj as a virtual bottom link, and there will be 6 joints between them so that the rigid objects can freely move. As the cube.obj has no collision body in the urdf, it will not influence the movement of the rigid object. Articulated objects will have one top link and one real bottom link, with one articulated joint defined.

Hope this can clarify!

Best,
Hui

**Comment by multi-graspllm** [comment]
Thank you for the detailed explanation! This clarifies my confusion perfectly.

**Comment by lihaosheng191240022** [comment]
Thank you for the detailed explanation! This clarifies my confusion perfectly.
