### ISSUE TITLE
Question about the two training phase

### ISSUE THREAD

**Issue by YliangWu** [zdchan/GraspXL#9]
Hello, your work is excellent！！！

I have a question about the code training part. Fixed and floating represent two stages of training. How are these two stages carried out? Is floating training performed after fixed training to specific iterations in the first stage? What is the iter in your experiment? I see  args.load_trained_policy is set to "store_true" in the floating runner and it is really bothering me.  

Looking forward to your help!!!

**Comment by zdchan** [comment]
Hi,

Thanks for the interest in our work. As explained in the paper, the policy is first trained with the fixed environment (the first phase), and then the trained policy is finetuned with the floating environment (the second phase, which means the args.load_trained_policy should be True by setting -re as an argument so that the policy trained in phase one can be loaded for further finetuning). 
You can stop training for either phase when you see the rewards converge, which means there is no fixed iteration number.

Hope this can help solve your questions, and feel free to ask if there is anything else unclear/

Best,
Hui

**Comment by YliangWu** [comment]
3QQQ!!!  I overlooked the paper on the curriculum section haha. Thanks!
